import {
    Home,
    Wifi,
    Building2,
    Zap,
    FileText,
    ShoppingCart,
    Utensils,
    Bus,
    Plane,
    CreditCard,
    ShoppingBag,
    Shirt,
    Dog,
    Smile,
    Pill,
    Car,
    Banknote,
    TrendingUp,
    LineChart,
    MoreHorizontal,
    Tag,
    Briefcase,
    Gift,
    Music,
    Video,
    Book,
    Coffee,
    Smartphone,
    Monitor,
    Headphones,
    Camera,
    Watch,
    Anchor,
    MapPin,
    Globe,
    Sun,
    Moon,
    Umbrella,
    CloudRain,
    Snowflake,
    Flame,
    Droplets,
    Hammer,
    Wrench,
    Construction,
    Sofa,
    Bed,
    Bath,
    ChefHat,
    Pizza,
    Beer,
    Wine,
    Baby,
    Gamepad,
    Dumbbell,
    Activity,
    Heart,
    Stethoscope,
    Syringe,
    GraduationCap,
    School,
    Trophy,
    Medal,
    Crown,
    Gem,
    Rocket,
    Wallet
} from 'lucide-react';

export const ICONS = {
    Home,
    Wifi,
    Building2,
    Zap,
    FileText,
    ShoppingCart,
    Utensils,
    Bus,
    Plane,
    CreditCard,
    ShoppingBag,
    Shirt,
    Dog,
    Smile,
    Pill,
    Car,
    Banknote,
    TrendingUp,
    LineChart,
    MoreHorizontal,
    Tag,
    Briefcase,
    Gift,
    Music,
    Video,
    Book,
    Coffee,
    Smartphone,
    Monitor,
    Headphones,
    Camera,
    Watch,
    Anchor,
    MapPin,
    Globe,
    Sun,
    Moon,
    Umbrella,
    CloudRain,
    Snowflake,
    Flame,
    Droplets,
    Hammer,
    Wrench,
    Construction,
    Sofa,
    Bed,
    Bath,
    ChefHat,
    Pizza,
    Beer,
    Wine,
    Baby,
    Gamepad,
    Dumbbell,
    Activity,
    Heart,
    Stethoscope,
    Syringe,
    GraduationCap,
    School,
    Trophy,
    Medal,
    Crown,
    Gem,
    Rocket,
    Wallet
};

// Map of Default Category IDs to Icon Names
export const DEFAULT_CATEGORY_ICONS = {
    'cat_housing': 'Home',
    'cat_internet': 'Wifi',
    'cat_condo': 'Building2',
    'cat_luz': 'Zap',
    'cat_taxes': 'FileText',
    'cat_supermarket': 'ShoppingCart',
    'cat_restaurant': 'Utensils',
    'cat_transport': 'Bus',
    'cat_travel': 'Plane',
    'cat_subscription': 'CreditCard',
    'cat_shopping': 'ShoppingBag',
    'cat_clothing': 'Shirt',
    'cat_pets': 'Dog',
    'cat_personal_care': 'Smile',
    'cat_pharmacy': 'Pill',
    'cat_car': 'Car',
    'cat_salary': 'Banknote',
    'cat_bonus': 'Gift',
    'cat_investments': 'TrendingUp',
    'cat_other': 'MoreHorizontal'
};

export const getIcon = (iconName) => {
    return ICONS[iconName] || ICONS.Tag;
};

export const getIconList = () => {
    return Object.keys(ICONS);
};
